body:
  - type: dropdown
    id: Creating_games_with_quest
    attributes:
      label: Which version of the Quest editor are you using?
      description: Let us know if you are using the Windows desktop version or the WebEditor app .
      options:
        - 
        - Windows desktop
        - Online/Web
      default: 0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Ask a question
      placeholder: Type here...
    validations:
      required: true
