body:
  - type: dropdown
    id: quest
    attributes:
      label: Which version of the Quest editor are you using?
      description: Let us know if you are using the WebEditor app or the Windows desktop version.
      options:
        - Windows desktop
        - Online/Web
      default: 0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Ask a Question
      placeholder: How do I ...
    validations:
      required: true
