body:
  - type: dropdown
    id: quest
    attributes:
      label: Which version of the Quest editor are you using?
      description: Let us know if you are using the Windows desktop version or the WebEditor app .
      options:
        - Windows desktop
        - Online/Web
      default: 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Add a body
      placeholder: Ask a question...
    validations:
      required: true
